using System;
using System.Reflection;
using System.Text;

namespace NGRID.Client.NGRIDServices
{
    /// <summary>
    /// Any NGRIDService class must be inherited from this class.
    /// </summary>
    public abstract class NGRIDService
    {
        #region Public properties

        /// <summary>
        /// When a method of a NGRIDService application is invoked, this field stores address of source application in NGRID.
        /// </summary>
        public NGRIDRemoteAppEndPoint RemoteApplication { get; internal set; }

        /// <summary>
        /// When a method of a NGRIDService application is invoked, this field stores the original message that is sent by NGRID server.
        /// </summary>
        public IIncomingMessage IncomingMessage { get; internal set; }

        #endregion

        #region Predefined Public Service Methods

        /// <summary>
        /// This method generates client proxy class to use this service.
        /// It is also a NGRIDServiceMethod, so, clients can update it's proxy classes via calling this method remotely.
        /// </summary>
        /// <param name="namespaceName">Namespace of generating proxy class</param>
        /// <returns>Proxy class code to use this service</returns>
        [NGRIDServiceMethod(Description = "This method generates client proxy class to use this service. Clients can update it's proxy classes via calling this method remotely.")]
        [return: NGRIDServiceMethodParameter("Proxy class code to use this service")]
        public string GenerateProxyClass([NGRIDServiceMethodParameter("Namespace of generating proxy class")] string namespaceName)
        {
            //Check parameters
            if (string.IsNullOrEmpty(namespaceName))
            {
                namespaceName = "NGRIDServiceProxies";
            }

            //Get this Type, Methods and Attributes
            var serviceType = GetType();
            var methods = serviceType.GetMethods();
            var attributes = serviceType.GetCustomAttributes(typeof(NGRIDServiceAttribute), true);

            //Check for NGRIDService attribute
            if (attributes.Length <= 0)
            {
                return "This class has not NGRIDService attribute. So, it is not a NGRIDService.";
            }

            //Get NGRIDService attribute
            var ngridServiceAttribute = (NGRIDServiceAttribute)attributes[0];

            //Generate class name
            var proxyClassName = serviceType.Name + "Proxy";

            //Start generating code
            var classBuilder = new StringBuilder();

            //Generate header of file.
            classBuilder.AppendLine("/* This code file is generated by NGRIDService Proxy Generator tool.");
            classBuilder.AppendLine(" * ");
            classBuilder.AppendLine(" * Service Name    : " + serviceType.Name);
            classBuilder.AppendLine(" * Service version : " + ngridServiceAttribute.Version);
            classBuilder.AppendLine(" * Generating date : " + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"));
            classBuilder.AppendLine(" */");
            classBuilder.AppendLine();

            //Namespaces
            classBuilder.AppendLine("using System;");
            classBuilder.AppendLine("using NGRID.Client;");
            classBuilder.AppendLine("using NGRID.Client.NGRIDServices;");
            classBuilder.AppendLine();

            //Class code
            classBuilder.AppendLine("namespace " + namespaceName);
            classBuilder.AppendLine("{");
            classBuilder.AppendLine("    /// <summary>");
            classBuilder.AppendLine("    /// This class is a proxy class to use " + serviceType.Name + " service.");
            if (!string.IsNullOrEmpty(ngridServiceAttribute.Description))
            {
                classBuilder.AppendLine("    /// Service Description: " + ngridServiceAttribute.Description);
            }

            classBuilder.AppendLine("    /// </summary>");
            classBuilder.AppendLine("    public partial class " + proxyClassName + " : NGRIDServiceProxyBase");
            classBuilder.AppendLine("    {");

            //Constructor
            classBuilder.AppendLine("        #region Constructor");
            classBuilder.AppendLine("        ");
            classBuilder.AppendLine("        /// <summary>");
            classBuilder.AppendLine("        /// Creates a new instance of " + proxyClassName + ".");
            classBuilder.AppendLine("        /// </summary>");
            classBuilder.AppendLine("        /// <param name=\"serviceConsumer\">Reference to a NGRIDServiceConsumer object to send/receive NGRID messages</param>");
            classBuilder.AppendLine("        /// <param name=\"remoteEndPoint\">Remote application end point to send requests</param>");
            classBuilder.AppendLine("        public " + proxyClassName + "(NGRIDServiceConsumer serviceConsumer, NGRIDRemoteAppEndPoint remoteEndPoint)");
            classBuilder.AppendLine("            : base(serviceConsumer, remoteEndPoint, \"" + serviceType.Name + "\")");
            classBuilder.AppendLine("        {");
            classBuilder.AppendLine("            ");
            classBuilder.AppendLine("        }");
            classBuilder.AppendLine("        ");
            classBuilder.AppendLine("        #endregion");
            classBuilder.AppendLine("        ");

            //Methods
            classBuilder.AppendLine("        #region " + serviceType.Name + " methods");
            classBuilder.AppendLine("        ");
            foreach (var method in methods)
            {
                if (IsPredefinedMethod(method.Name))
                {
                    continue;
                }

                WriteMethod(classBuilder, method);
            }

            classBuilder.AppendLine("        #endregion");
            classBuilder.AppendLine("        ");
            classBuilder.AppendLine("        #region Default (predefined) service methods");
            classBuilder.AppendLine("        ");
            foreach (var method in methods)
            {
                if (!IsPredefinedMethod(method.Name))
                {
                    continue;
                }

                WriteMethod(classBuilder, method);
            }

            classBuilder.AppendLine("        #endregion");

            //Close class
            classBuilder.AppendLine("    }");

            //Close namespace
            classBuilder.AppendLine("}");

            return classBuilder.ToString();
        }

        /// <summary>
        /// This method can be used to check if service is available.
        /// </summary>
        /// <param name="message">A string message</param>
        /// <returns>Reply to message as formatted: "RE:message".</returns>
        [NGRIDServiceMethod(Description = "This method can be used to check if service is available.")]
        [return: NGRIDServiceMethodParameter("Reply to message as formatted: 'RE: message'")]
        public string CheckServiceIsAvailable([NGRIDServiceMethodParameter("A message to reply")] string message)
        {
            return ("RE: " + message);
        }

        #endregion

        #region Private methods

        private static void WriteMethod(StringBuilder classBuilder, MethodInfo method)
        {
            //Check for NGRIDServiceMethod attribute
            var methodAttributes = method.GetCustomAttributes(typeof(NGRIDServiceMethodAttribute), true);
            if (methodAttributes.Length <= 0)
            {
                return;
            }

            //Get NGRIDServiceMethod attribute
            var serviceMethodAttribute = (NGRIDServiceMethodAttribute)methodAttributes[0];

            //Get return type
            var returnType = NormalizeType(method.ReturnType.Name);

            //Get parameters
            var parameters = method.GetParameters();

            //Generate proxy method arguments and invoke method parameters
            var methodArgumentsString = new StringBuilder();
            var invokeParameters = new StringBuilder();
            foreach (var parameter in parameters)
            {
                var paramType = NormalizeType(parameter.ParameterType.Name);
                if (methodArgumentsString.Length > 0)
                {
                    methodArgumentsString.Append(", ");
                }

                methodArgumentsString.Append(paramType + " " + parameter.Name);
                invokeParameters.Append(", " + parameter.Name);
            }

            //Generate method summary
            classBuilder.AppendLine("        /// <summary>");
            classBuilder.AppendLine("        /// " + (serviceMethodAttribute.Description ?? "No method summary available."));
            classBuilder.AppendLine("        /// </summary>");

            //Generate XML-Comments for parameters
            foreach (var parameter in parameters)
            {
                var paramAttributes = parameter.GetCustomAttributes(typeof(NGRIDServiceMethodParameterAttribute), true);
                if (paramAttributes.Length <= 0)
                {
                    continue;
                }

                classBuilder.AppendLine("        /// <param name=\"" + parameter.Name + "\">" + ((NGRIDServiceMethodParameterAttribute)paramAttributes[0]).Description + "</param>");
            }

            //Generate XML-Comments for return value
            if (returnType != "void")
            {
                var returnAttributes = method.ReturnParameter.GetCustomAttributes(typeof(NGRIDServiceMethodParameterAttribute), true);
                if (returnAttributes.Length > 0)
                {
                    classBuilder.AppendLine("        /// <returns>" + ((NGRIDServiceMethodParameterAttribute)returnAttributes[0]).Description + "</returns>");
                }
            }

            //Generate method signature and opening bracket
            classBuilder.AppendLine("        public " + returnType + " " + method.Name + "(" + methodArgumentsString + ")");
            classBuilder.AppendLine("        {");

            //Generate method body according to return value
            if (returnType == "void")
            {
                classBuilder.AppendLine("            InvokeRemoteMethod(\"" + method.Name + "\"" + invokeParameters + ");");
            }
            else
            {
                classBuilder.AppendLine("            return (" + returnType + ") InvokeRemoteMethodAndGetResult(\"" + method.Name + "\"" + invokeParameters + ");");
            }

            //Method closing bracket
            classBuilder.AppendLine("        }");
            classBuilder.AppendLine("        ");
        }

        /// <summary>
        /// Normalizes some known primitive types.
        /// </summary>
        /// <param name="typeName">Type name</param>
        /// <returns>Normalized type name</returns>
        private static string NormalizeType(string typeName)
        {
            switch (typeName)
            {
                case "Void":
                    return "void";
                case "Boolean":
                    return "bool";
                case "Byte":
                    return "byte";
                case "Byte[]":
                    return "byte[]";
                case "Int16":
                    return "short";
                case "Int16[]":
                    return "short[]";
                case "Int32":
                    return "int";
                case "Int32[]":
                    return "int[]";
                case "Int64":
                    return "long";
                case "Int64[]":
                    return "long[]";
                case "String":
                    return "string";
                case "String[]":
                    return "string[]";
                case "Single":
                    return "float";
                case "Single[]":
                    return "float[]";
                case "Double":
                    return "double";
                case "Double[]":
                    return "double[]";
            }

            //Not known type
            return typeName;
        }

        /// <summary>
        /// Checks if a method is predefined method (NGRIDService methods in NGRIDService class).
        /// </summary>
        /// <param name="methodName">Method name to check</param>
        /// <returns>True: Yes, it is..</returns>
        private static bool IsPredefinedMethod(string methodName)
        {
            return (methodName == "GenerateProxyClass" || methodName == "CheckServiceIsAvailable");
        }

        #endregion
    }
}
